version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  pypi-release:
    docker:
      - image: cimg/python:3.11.9
    steps:
      - checkout
      - run:
          name: Install Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python3 -
      - run:
          name: Install Dependencies
          command: poetry install
      - run_tests
      - create_pip_package
      - upload_to_index

commands:
  run_tests:
    steps:
      - run:
          name: Unit tests
          command: |
            poetry run python -m unittest discover -s ./tests -p 'test_*.py'
            
  create_pip_package:
    steps:
      - run:
          name: Create package
          command: |
            poetry build
            
  upload_to_index:
    steps:
      - run:
          name: Upload to index
          command: |
            export POETRY_PYPI_TOKEN_PYPI="${TWINE_PASSWORD}"
            poetry publish

workflows:
  main:
    jobs:
      - pypi-release:
          context: 
            - python-packages
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
