version: 2.1

orbs:
  python: circleci/python@2.1.1

commands:
  run_tests:
    steps:
      - run:
          name: Unit tests
          command: |
            git checkout -b test-branch-`git rev-parse --short HEAD`
            python -m unittest discover -s ./tests -p 'test_*.py'
            
  create_pip_package:
    steps:
      - run:
          name: Create package
          command: |
            python setup.py clean --all
            python setup.py bdist_wheel
            
  upload_to_index:
    parameters:
      index:
        default: "pypi"
        type: string
      username:
        default: "__token__"
        type: string
      password:
        default: $PROD_PYPI_TOKEN
        type: string
    steps:
      - run:
          name: Upload to index
          command: |
            export TWINE_USERNAME="<< parameters.username >>"
            export TWINE_PASSWORD="<< parameters.password >>"
            twine upload -r <<parameters.index>> dist/*

jobs:
  pypi-release:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run_tests
      - create_pip_package
      - upload_to_index

workflows:
  main:
    jobs:
      - pypi-release:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
