version: 2.1

orbs:
  python: circleci/python@2.1.1

commands:
  run_tests:
    steps:
      - run:
          name: Unit tests
          command: |
            git checkout -b test-branch-`git rev-parse --short HEAD`
            python -m unittest discover -s ./tests -p 'test_*.py'

  create_pip_package:
    steps:
      - run:
          name: Create package
          command: |
            poetry build
  upload_to_index:
    parameters:
      index:
        default: "pypi"
        type: string
      username:
        default: "__token__"
        type: string
      password:
        default: $PYPI_TOKEN
        type: string
    steps:
      - run:
          name: Upload to index
          command: |
            poetry config pypi-token.pypi $PROD_PYPI_TOKEN
            poetry publish
jobs:
  pypi-release:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python3 -
      - run:
          name: Install Dependencies
          command: poetry install
      - run_tests
      - create_pip_package
      - upload_to_index

workflows:
  main:
    jobs:
      - pypi-release:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
